name: Convert All DOCX/DOC to Markdown

on: 
  push:
    paths:
      - '**/*.docx'
      - '**/*.DOCX'
      - '**/*.doc'
      - '**/*.DOC'

jobs:
  convert_doc_to_md:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Convert DOCX/DOC to Markdown
        run: |
          for file in $(find . -iname "*.docx" -o -iname "*.doc"); do
            pandoc "$file" -o "${file%.*}.md"
          done
          
      - name: Commit Changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add *.md
          git commit -m "Convert DOCX/DOC to Markdown"
          git push

