name: Convert All DOCX/DOC to Markdown

on: 
  push:
    paths:
      - '**/*.docx'
      - '**/*.DOCX'
      - '**/*.doc'
      - '**/*.DOC'
  workflow_dispatch:

jobs:
  convert_doc_to_md:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Convert DOCX/DOC to Markdown
        run: |
          find . -iname "*.docx" -o -iname "*.doc" | while read -r file; do
            pandoc "$file" -o "${file%.*}.md"
          done
          
      - name: Commit Changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add *.md
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Convert DOCX/DOC to Markdown"
            git push
          fi

