name: Convert All Markdown to DOCX

on: 
  push:
    paths:
      - '**/*.md'
  workflow_dispatch:

jobs:
  convert_md_to_docx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Convert Markdown to DOCX
        run: |
          find . -iname "*.md" ! -iname "LICENSE.md" ! -iname "README.md" | while read -r file; do
            pandoc "$file" -o "${file%.*}.docx"
          done
          
      - name: Commit Changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add *.docx
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Convert Markdown to DOCX"
            git push
          fi

